### ISSUE TITLE
Error excecude generate_traning_data.py windows

### ISSUE THREAD

**Issue by popurax** [marshq/europilot#1]
I'd like to run it in Windows .
I installed the required libraries such as scipy and opencv-python, but running `python generate_training_data.py` from the command line will cause an error.
What should I do?

scripts/generate_training_data.py
```python
from europilot.screen import Box
from europilot.train import generate_training_data, Config

class MyConfig(Config):
    # Screen area
    BOX = Box(2, 29, 1282, 797)	# "python select_screen_area.py"
    # Screen capture fps
    DEFAULT_FPS = 20
    DATA_PATH = "C:\europilot\mydata" # Error 'Invalid data path: ', add code
    IMG_PATH = "C:\europilot\mydata"  # Error 'Invalid image path: ', add code

generate_training_data(config=MyConfig)
```

execude & stack trace
```
C:\europilot\scripts>python generate_training_data.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\europilot\scripts\generate_training_data.py", line 12, in <module>
    generate_training_data(config=MyConfig)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\site-packages\europilot-0.0.1-py3.5.egg\europilot\train.py", line 223, in generate_training_data
    worker.start()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\europilot\scripts\generate_training_data.py", line 12, in <module>
    run_name="__mp_main__")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
    run_name="__mp_main__")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    exec(code, run_globals)
  File "C:\europilot\scripts\generate_training_data.py", line 12, in <module>
    generate_training_data(config=MyConfig)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\site-packages\europilot-0.0.1-py3.5.egg\europilot\train.py", line 223, in generate_training_data
    generate_training_data(config=MyConfig)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\site-packages\europilot-0.0.1-py3.5.egg\europilot\train.py", line 223, in generate_training_data
    worker.start()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    worker.start()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    self._popen = self._Popen(self)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    exec(code, run_globals)
  File "C:\europilot\scripts\generate_training_data.py", line 12, in <module>
    generate_training_data(config=MyConfig)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\site-packages\europilot-0.0.1-py3.5.egg\europilot\train.py", line 223, in generate_training_data
    worker.start()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    _check_not_importing_main()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    run_name="__mp_main__")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\europilot\scripts\generate_training_data.py", line 12, in <module>
    generate_training_data(config=MyConfig)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\site-packages\europilot-0.0.1-py3.5.egg\europilot\train.py", line 223, in generate_training_data
    worker.start()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._popen = self._Popen(self)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by daftshady** [comment]
Please read a compatibility section in README. We haven't tested europilot on windows yet. We should meet some constraints to use python multiprocessing module properly on windows and `freeze_support()` is one of them. And some other things which seem to be fragile on windows occurs to my mind. We have a window support on our roadmap, but a priority is low. You can also make a PR if you are interested in it.
